"""Порты репозиториев. Типизированы на domain.entities."""
from __future__ import annotations

from typing import Protocol


class AccountStore(Protocol):
    async def create_user(self, username: str, password_hash: str) -> str: ...
    async def get_by_username(self, username: str) -> tuple[str, str, str] | None: ...
    async def create_session(
        self, user_id: str, token_hash: str, expires_at: str
    ) -> None: ...
    async def delete_session(self, token_hash: str) -> None: ...
    async def user_for_token_hash(self, token_hash: str) -> tuple[str, str] | None: ...
