"""Порты репозиториев. Типизированы на domain.entities."""
from __future__ import annotations

from datetime import datetime
from typing import Protocol


class AccountStore(Protocol):
    async def create_user(
        self, username: str, password_hash: str, role: str = "user"
    ) -> str: ...
    async def get_by_username(
        self, username: str
    ) -> tuple[str, str, str, str] | None: ...
    async def update_password(self, username: str, password_hash: str) -> None: ...
    async def create_session(
        self, user_id: str, token_hash: str, expires_at: str
    ) -> None: ...
    async def delete_session(self, token_hash: str) -> None: ...
    async def user_for_token_hash(
        self, token_hash: str
    ) -> tuple[str, str, str] | None: ...
    async def list_users(self) -> list[tuple[str, str, datetime]]: ...
    async def set_role(
        self, username: str, role: str
    ) -> tuple[str, str, datetime] | None: ...
    async def delete_user(self, username: str) -> bool: ...
    async def count_admins(self) -> int: ...
