from __future__ import annotations

from typing import Protocol


class AccountStore(Protocol):
    def create_user(self, username: str, password_hash: str) -> str: ...
    def get_by_username(self, username: str) -> tuple[str, str, str] | None: ...
    def create_session(self, user_id: str, token_hash: str, expires_at: str) -> None: ...
    def delete_session(self, token_hash: str) -> None: ...
    def user_for_token_hash(self, token_hash: str) -> tuple[str, str] | None: ...
